In [1]:
import numpy as np
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
c=a+b
d=a-b
e=a*b 
f=np.dot(a,b)
at=a.T
print("Addition")
print(c)
print("Substraction")
print(d)
print("Multiplication(element)")
print(e)
print("Multiplication(row)")
print(f)
print("Transpose")
print(at)

Addition
[[ 6  8]
 [10 12]]
Substraction
[[-4 -4]
 [-4 -4]]
Multiplication(element)
[[ 5 12]
 [21 32]]
Multiplication(row)
[[19 22]
 [43 50]]
Transpose
[[1 3]
 [2 4]]


In [2]:
#create a sample matrix
x=np.array([[1,2,3],[4,5,6],[7,8,9]])
#perform SVD
U,S,VT=np.linalg.svd(x)
#choose the number of components to keep
n_components=2
#reconstructed the matrix with reduced dimensions
x_reconstructed=np.dot(U[:,:n_components],np.dot(np.diag(S[:n_components]),VT[:n_components,:]))
print("original matrix:")
print(x)
print("\nReconstructed matrix(with reduced dimensions):")
print(x_reconstructed)


original matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Reconstructed matrix(with reduced dimensions):
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
